// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzA1IO5pf6_d_hJVfNVh2CONGC2ul25rw',
    appId: '1:902009033553:web:fe2c5a75f4c41cc767b970',
    messagingSenderId: '902009033553',
    projectId: 'my-flutter-notes-cec3a',
    authDomain: 'my-flutter-notes-cec3a.firebaseapp.com',
    storageBucket: 'my-flutter-notes-cec3a.appspot.com',
    measurementId: 'G-FWN36TETZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGf2DzsOmaEWm88fQuRy_sPLK0-DyEYvg',
    appId: '1:902009033553:android:0af248c09761a33b67b970',
    messagingSenderId: '902009033553',
    projectId: 'my-flutter-notes-cec3a',
    storageBucket: 'my-flutter-notes-cec3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEcTvcjRIbHJoEZWpaD2oKo3MJhAwDmko',
    appId: '1:902009033553:ios:5a7184f72bd96ce967b970',
    messagingSenderId: '902009033553',
    projectId: 'my-flutter-notes-cec3a',
    storageBucket: 'my-flutter-notes-cec3a.appspot.com',
    iosClientId: '902009033553-ght78fsip77kmeub8jjk2l8rr96tonsi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
